# CMake generated Testfile for 
# Source directory: /home/wissem/workspace/open-lotto
# Build directory: /home/wissem/workspace/open-lotto/build-sanitizer
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(unit_combogen "/home/wissem/workspace/open-lotto/build-sanitizer/test_combogen")
set_tests_properties(unit_combogen PROPERTIES  PASS_REGULAR_EXPRESSION "Tests passed:" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;286;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(unit_plugin_loader "/home/wissem/workspace/open-lotto/build-sanitizer/test_plugin_loader")
set_tests_properties(unit_plugin_loader PROPERTIES  PASS_REGULAR_EXPRESSION "Tests passed:" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;315;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(unit_export "/home/wissem/workspace/open-lotto/build-sanitizer/test_export")
set_tests_properties(unit_export PROPERTIES  PASS_REGULAR_EXPRESSION "Tests passed:" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;331;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(unit_localization "/home/wissem/workspace/open-lotto/build-sanitizer/test_localization")
set_tests_properties(unit_localization PROPERTIES  PASS_REGULAR_EXPRESSION "Tests passed:" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;343;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(unit_dev_api "/home/wissem/workspace/open-lotto/build-sanitizer/test_dev_api")
set_tests_properties(unit_dev_api PROPERTIES  PASS_REGULAR_EXPRESSION "Tests passed:" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;364;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(unit_historical_db "/home/wissem/workspace/open-lotto/build-sanitizer/test_historical_db")
set_tests_properties(unit_historical_db PROPERTIES  PASS_REGULAR_EXPRESSION "Tests passed:" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;381;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(cli_lists_games "/home/wissem/workspace/open-lotto/build-sanitizer/open-lotto" "--list-games")
set_tests_properties(cli_lists_games PROPERTIES  PASS_REGULAR_EXPRESSION "Eurojackpot|EuroJackpot" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;391;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(cli_runs_lotto_once "/home/wissem/workspace/open-lotto/build-sanitizer/open-lotto" "--game" "Lotto 6aus49" "--draws" "1")
set_tests_properties(cli_runs_lotto_once PROPERTIES  PASS_REGULAR_EXPRESSION "Main:" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;398;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(cli_runs_eurojackpot_once "/home/wissem/workspace/open-lotto/build-sanitizer/open-lotto" "--game" "Eurojackpot" "--draws" "1")
set_tests_properties(cli_runs_eurojackpot_once PROPERTIES  PASS_REGULAR_EXPRESSION "Main:" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;405;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(cli_seed_reproducible "bash" "/home/wissem/workspace/open-lotto/tests/test_cli_seed_repro.sh" "/home/wissem/workspace/open-lotto/build-sanitizer/open-lotto")
set_tests_properties(cli_seed_reproducible PROPERTIES  PASS_REGULAR_EXPRESSION "seed reproducibility OK" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;412;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(cli_reloads_selected_plugin "/home/wissem/workspace/open-lotto/build-sanitizer/open-lotto" "--game" "Lotto 6aus49" "--reload-plugin" "--validate-only")
set_tests_properties(cli_reloads_selected_plugin PROPERTIES  PASS_REGULAR_EXPRESSION "Plugin reload: enabled" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;419;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(cli_syncs_historical_db_latest "/home/wissem/workspace/open-lotto/build-sanitizer/open-lotto" "--game" "Eurojackpot" "--database-gewinnzahlen" "update")
set_tests_properties(cli_syncs_historical_db_latest PROPERTIES  ENVIRONMENT "OPEN_LOTTO_GEWINNZAHLEN_URL_EUROJACKPOT=file:///home/wissem/workspace/open-lotto/tests/data/eurojackpot_gewinnzahlen.json" PASS_REGULAR_EXPRESSION "Local historical database" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;426;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(cli_historical_db_unsupported_game "/home/wissem/workspace/open-lotto/build-sanitizer/open-lotto" "--game" "Lotto 6aus49" "--database-gewinnzahlen" "update")
set_tests_properties(cli_historical_db_unsupported_game PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;434;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(plugin_validator_accepts_valid_plugin "/home/wissem/workspace/open-lotto/build-sanitizer/open-lotto-plugin-validator" "/home/wissem/workspace/open-lotto/build-sanitizer/plugins/liblotto.so")
set_tests_properties(plugin_validator_accepts_valid_plugin PROPERTIES  PASS_REGULAR_EXPRESSION "VALID Lotto 6aus49" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;439;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(plugin_validator_rejects_invalid_plugin "/home/wissem/workspace/open-lotto/build-sanitizer/open-lotto-plugin-validator" "/home/wissem/workspace/open-lotto/build-sanitizer/plugins/libstub_plugin.so")
set_tests_properties(plugin_validator_rejects_invalid_plugin PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;446;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(cli_no_args "/home/wissem/workspace/open-lotto/build-sanitizer/open-lotto")
set_tests_properties(cli_no_args PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;454;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(cli_missing_game_flag "/home/wissem/workspace/open-lotto/build-sanitizer/open-lotto" "Lotto 6aus49")
set_tests_properties(cli_missing_game_flag PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;459;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(cli_draws_zero "/home/wissem/workspace/open-lotto/build-sanitizer/open-lotto" "--game" "Lotto 6aus49" "--draws" "0")
set_tests_properties(cli_draws_zero PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;464;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(cli_draws_negative "/home/wissem/workspace/open-lotto/build-sanitizer/open-lotto" "--game" "Lotto 6aus49" "--draws" "-1")
set_tests_properties(cli_draws_negative PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;469;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(cli_draws_not_a_number "/home/wissem/workspace/open-lotto/build-sanitizer/open-lotto" "--game" "Lotto 6aus49" "--draws" "abc")
set_tests_properties(cli_draws_not_a_number PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;474;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(cli_draws_missing_value "/home/wissem/workspace/open-lotto/build-sanitizer/open-lotto" "--game" "Lotto 6aus49" "--draws")
set_tests_properties(cli_draws_missing_value PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;479;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(cli_invalid_export_format "/home/wissem/workspace/open-lotto/build-sanitizer/open-lotto" "--game" "Lotto 6aus49" "--draws" "1" "--export" "xml")
set_tests_properties(cli_invalid_export_format PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;484;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(cli_export_missing_value "/home/wissem/workspace/open-lotto/build-sanitizer/open-lotto" "--game" "Lotto 6aus49" "--draws" "1" "--export")
set_tests_properties(cli_export_missing_value PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;489;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(cli_unknown_flag "/home/wissem/workspace/open-lotto/build-sanitizer/open-lotto" "--game" "Lotto 6aus49" "--invalid-flag")
set_tests_properties(cli_unknown_flag PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;494;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(cli_seed_invalid_value "/home/wissem/workspace/open-lotto/build-sanitizer/open-lotto" "--game" "Lotto 6aus49" "--seed" "not_a_number")
set_tests_properties(cli_seed_invalid_value PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;499;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(cli_verbose_missing_value "/home/wissem/workspace/open-lotto/build-sanitizer/open-lotto" "--game" "Lotto 6aus49" "--verbose")
set_tests_properties(cli_verbose_missing_value PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;504;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(unit_property "/home/wissem/workspace/open-lotto/build-sanitizer/test_property")
set_tests_properties(unit_property PROPERTIES  PASS_REGULAR_EXPRESSION "Tests passed:" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;551;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(unit_stress "/home/wissem/workspace/open-lotto/build-sanitizer/test_stress")
set_tests_properties(unit_stress PROPERTIES  PASS_REGULAR_EXPRESSION "Tests passed:" TIMEOUT "120" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;569;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
add_test(unit_perf_regression "/home/wissem/workspace/open-lotto/build-sanitizer/test_perf_regression")
set_tests_properties(unit_perf_regression PROPERTIES  PASS_REGULAR_EXPRESSION "Tests passed:" TIMEOUT "120" _BACKTRACE_TRIPLES "/home/wissem/workspace/open-lotto/CMakeLists.txt;589;add_test;/home/wissem/workspace/open-lotto/CMakeLists.txt;0;")
